spring:
  application:
    name: qbp
  profiles:
    active: dev

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认7天）
  expireTime: 604800


secure:
  ignored:
    urls:
      - /register
      - /captchaImage
      - /login
