spring:
  datasource:
    url: jdbc:mysql://localhost:3306/questionbankpro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1  # Redis 服务器地址
    database: 0  # 使用的Redis数据库编号
    port: 6379  # Redis 服务器端口
    password: ''  # Redis 服务器密码（如果设置了密码）
    timeout: 3000ms  # 连接超时时间
